# Generated by Django 3.0.5 on 2020-04-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braSize', models.FloatField()),
                ('height', models.FloatField()),
                ('head', models.FloatField()),
                ('neck', models.FloatField()),
                ('upperBust', models.FloatField()),
                ('bust', models.FloatField()),
                ('nippleToNipple', models.FloatField()),
                ('nippleToShoulder', models.FloatField()),
                ('underBust', models.FloatField()),
                ('waist', models.FloatField()),
                ('highHip', models.FloatField()),
                ('hip', models.FloatField()),
                ('shoulderWidth', models.FloatField()),
                ('bicep', models.FloatField()),
                ('wrist', models.FloatField()),
                ('insideArm', models.FloatField()),
                ('aroundKnuckle', models.FloatField()),
                ('topOfThigh', models.FloatField()),
                ('insideLegToHeel', models.FloatField()),
                ('aroundKnee', models.FloatField()),
                ('aroundCalf', models.FloatField()),
                ('aroundAnkle', models.FloatField()),
                ('footWidth', models.FloatField()),
                ('belowButtockToheel', models.FloatField()),
                ('frontWaistToHeel', models.FloatField()),
                ('frontWaistToBelowKnee', models.FloatField()),
                ('NeckToWaist', models.FloatField()),
                ('waistToCrotchLine', models.FloatField()),
                ('underBustToWaist', models.FloatField()),
                ('rise', models.FloatField()),
                ('NapeToWaist', models.FloatField()),
                ('neckToShoulder', models.FloatField()),
                ('underarmToWaist', models.FloatField()),
            ],
        ),
    ]
